$(document).ready(function(){
    $('.type_card_test_R').hover(function(){
        $('.type_card_test_R').toggleClass('expanding');
    });
    $('.type_card_test_I').hover(function(){
        $('.type_card_test_I').toggleClass('expanding');
    });
    $('.type_card_test_A').hover(function(){
        $('.type_card_test_A').toggleClass('expanding');
    });
    $('.type_card_test_S').hover(function(){
        $('.type_card_test_S').toggleClass('expanding');
    });
    $('.type_card_test_E').hover(function(){
        $('.type_card_test_E').toggleClass('expanding');
    });
    $('.type_card_test_C').hover(function(){
        $('.type_card_test_C').slideToggle('expanding');
    });
})

